version: "3"

services:
  server:
    # docekrfile 경로
    image: tree0204/drf_tuto:0.1.0
    build: ./
    volumes:
      - /service=./
    command:
      - bash
      - -c
      - |
        python manage.py collectstatic --no-input
        python manage.py migrate
    ports:
      - 8000:8000
    depends_on:
      - sqlite3
    networks:
      - web_network
    deploy:
      replicas: 3
      placement:
        constraints: [node.hostname==ip-172-31-33-220]
      resources:
        limits:
          memory: 10M
        reservations:
          memory: 10M
          cpus: "0.1"
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - /db=./db.sqlite3
    networks:
      - web_network
    deploy:
      replicas: 3

networks:
  web_network:
