version: "3"

services:
  server:
    # docekrfile 경로
    image: tree0204/drf_tuto:0.1.0
    build: ./
    volumes:
      - /usr/src/app
    command:
      - bash
      - -c
      - |
        python manage.py collectstatic --no-input
        python manage.py migrate
    ports:
      - 8000:8000
    depends_on:
      - sqlite3
    deploy:
      replicas: 2
      placement:
        constraints: [node.role==manager]
      resources:
        limits:
          memory: 10M
        reservations:
          memory: 10M
          cpus: "0.1"
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 2

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - /db=./db.sqlite3
    deploy:
      replicas: 2
      placement:
        constraints: [node.role==worker]

  Swarm_Cluster:
    image: dockersamples/visualizer
    ports:
      - 8881:8000
    deploy:
      replicas: 1
      placement:
        constraints: [node.role==manager]
