version: "3"

services:
  server:
    # docekrfile 경로
    image: tree0204/drf_tuto:0.1.0
    build: ./:/usr/src/app
    command:
      - bash
      - -c
      - |
        python manage.py collectstatic --no-input
        python manage.py migrate
    ports:
      - 8000:8000
    depends_on:
      - sqlite3
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 50M
        reservations:
          memory: 20M
          cpus: "0.1"
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - /server=./db.sqlite3
    deploy:
      replicas: 3
