version: "3"

services:
  server:
    # docekrfile 경로
    image: tree0204/drf_tuto:latest
    build: ./
    volumes:
      - ./:/usr/src/app
    command:
      - bash
      - -c
      - |
        python manage.py collectstatic --no-input
        python manage.py migrate
    ports:
      - 8000:8000
    depends_on:
      - sqlite3
    deploy:
      placement:
        constraints:
          - node.role==manager
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./:./db.sqlite3
    deploy:
      replicas: 3
